os: linux
dist: focal

language: node_js
node_js:
  - '14'

addons:
  chrome: stable
  ssh_known_hosts:
    - host.lgbt
    - 104.155.163.15

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox || travis_terminate 1;
  - ng build --prod
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/HimitsuFrontend/ mattie@host.lgbt:~/wwwhome/franel.net/
  on:
    branch: master
    tags: true